# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: windows-latest

#Build stage
stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        displayName: Build job
        steps:
        - task: Maven@3
          displayName: maven pom file
          inputs:
            mavenPomFile: 'app/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: CopyFiles@2
          displayName: 'Copy Files to target'
          inputs:
            SourceFolder: '$(system.defaultworkingdirectory)'
            Contents: '**/app/gradle/wrapper/gradle-wrapper.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          displayName: ' drop'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'

#Deploy stage
  - stage: "Deploy"
    jobs:
      - job: "Deploy"
        displayName: Deploy Job
        steps:
         - task: DownloadBuildArtifacts@1
           displayName: Download Artifact
           inputs:
              buildType: 'current'
              downloadType: 'specific'
              downloadPath: '$(System.ArtifactsDirectory)'
         - task: AzureRmWebAppDeployment@4
           displayName:  Web app Deploy
           inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Sathvik Azure'
              appType: 'webApp'
              WebAppName: 'Webapp-eus-002'
              packageForLinux: 'D:\a\1\a\drop/app/gradle/wrapper/gradle-wrapper.jar'